class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :download_outline]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
    @task
    @note = Note.new
  end

  def new
    @task = Task.new
    # Allow adding a Note in the simple_form, not requiring a separate form
    @task.notes.build # Prepare one Note model field in the #new form
    @task.build_outline
  end

  def create
    @task = current_user.tasks.new(task_params)
    # Assign an empty string to the Outline record contents. This makes view handling & record checking easier,
    # plus we'll always need the field anyhow. Otherwise, the child outline record would be NIL until saved with :contents
    # containing some value (non-empty field)
    @task.outline.contents = ""

    if @task.save!
      redirect_to task_path(@task), notice: "✔ Task created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task
    @note = Note.new
    @outline = Outline.new
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render edit_task_path(@task), notice: "✖ Task edit failed"
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  def download_outline

    format_type = params[:format_type]
    text_contents = clean_markdown_contents(@task.outline.contents)

    if format_type == 'txt'
      send_data text_contents,
      filename: "#{@task.title.parameterize}.txt",
      type: "text/plain",
      disposition: "attachment"
    elsif format_type == 'pdf'
      pdf_file = generate_pdf(@task.title, text_contents)
      send_data pdf_file,
      filename: "#{@task.title.parameterize}.pdf",
      type: "application/pdf",
      disposition: "attachment"             
    end
  end 

  def generate_pdf(title, text)
    # Support PDF generation
    require "prawn"

    Prawn::Document.new do |pdf|
      pdf.text "Writing task outline", size: 20, style: :bold
      pdf.text "Title: #{title}", size: 20, style: :bold
      pdf.move_down 10
      pdf.text text, size: 16
    end.render
  end

  def clean_markdown_contents(text)
    # Removes Markdown '#' characters before a download - should not be needed for typical outpline
    # format generated by AI agent for the user. Uses regex express for 1+ '#' chars. followed by a whitespace
    # Also removes one or more asterisks (Markdown for bold, italics)
    cleaned = text.gsub(/\#+\s/, '')
    cleaned.gsub(/\*+/, '')
  end
  
  # #####################################################
  
  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :title, :synopsis,
      notes_attributes: [:id, :text],
      outline_attributes: [:id, :contents]
    )
  end

end
